/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.List;

public class AppTest {

<<<<<<< HEAD
=======
class AppTest {
    @Test 
    public void testTask4(){
        List<Integer> x = List.of( 1 , 2 , 3 , 4 , 5);
        List<Integer> y = List.of(5 , 4 , 3 , 2 , 1);
        List<Integer> result = List.of(1 , 4, 9, 16, 25);
        assertEquals(result , SimpleFunctions.Task4(x,y) , "Values should be correctly multiplied");

    }

    @Test 
    public void testTask4_2(){
        List<Integer> x = List.of(1,2,3);
        List<Integer> b = List.of(1,3);
        assertEquals(null , SimpleFunctions.Task4(x,b) ,"Lists can not be different sizes");

    }

    @Test
    public void Task4_EqualSizeLists_CorrectResult() {
        // Arrange
        SimpleFunctions sf = new SimpleFunctions();
        List<Integer> a = Arrays.asList(1, 2, 3, 4);
        List<Integer> b = Arrays.asList(5, 6, 7, 8);
        List<Integer> expected = Arrays.asList(8, 14, 18, 20);
        
        // Act
        List<Integer> result = sf.Task4(a, b);

        // Assert
        assertIterableEquals(expected, result);
    }

    @Test
    public void Task4_DifferentSizeLists() {
        // Arrange
        SimpleFunctions sf = new SimpleFunctions();
        List<Integer> a = Arrays.asList(1, 2, 3, 4);
        List<Integer> b = Arrays.asList(5, 6, 7);

        // Act
        List<Integer> result = sf.Task4(a, b);

        // Assert
        assertNull(result);
    }

    @Test
    public void testTask6(){
        List<Integer> x = List.of(101,303,404,202,505);
        List<Integer> result = List.of(200,400,500,300,600);
        assertEquals(result , SimpleFunctions.tasksix(x), "Make sure function rounds up correctly");
    }

    @Test 
    public void testTask6_2(){
        List<Integer> x = List.of(100,200,300,567);
        List<Integer> result = List.of(100,200,300,600);
        assertEquals(result, SimpleFunctions.tasksix(x), "If a number is already a multiple, it does not round up");
    }
>>>>>>> 1dd327500baf39547b81a57b7cd28167823719cd
}
